/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import devoo.Troncon;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author tanguyhelesbeux
 */
public class VueTroncon extends javax.swing.JPanel {
    
    private Troncon troncon;

    /**
     * Creates new form VueTroncon
     */
    public VueTroncon() {
        initComponents();
    }

    public VueTroncon(Troncon troncon) {
        initComponents();
        this.setTroncon(troncon);
        this.setVisible(true);
        this.setOpaque(false);
        this.setBackground(Color.BLACK);
    }

    public Troncon getTroncon() {
        return troncon;
    }

    public void setTroncon(Troncon troncon) {
        this.troncon = troncon;
        
        int x = Math.min(this.getTroncon().depart.x, this.getTroncon().arrivee.x);
        int y = Math.min(this.getTroncon().depart.y, this.getTroncon().arrivee.y);
        this.setLocation(x, y);
        
        int width = Math.abs(this.getTroncon().arrivee.x - this.getTroncon().depart.x);
        int height = Math.abs(this.getTroncon().arrivee.y - this.getTroncon().depart.y);
        this.setSize(width, height);
    }
    
        @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(Color.gray);
        Graphics2D g2D = (Graphics2D) g;
        g2D.setStroke(new BasicStroke(4));
        
        int xDepart, yDepart, xArrivee, yArrivee;
        
        if (this.getTroncon().depart.x > this.getTroncon().arrivee.x) {
            xDepart = this.getWidth();
            xArrivee = 0;
        } else {
            xDepart = 0;
            xArrivee = this.getWidth();
        }
        
        if (this.getTroncon().depart.y > this.getTroncon().arrivee.y) {
            yDepart = this.getHeight();
            yArrivee = 0;
        } else {
            yDepart = 0;
            yArrivee = this.getHeight();
        }
        
        g.drawLine(xDepart, yDepart, xArrivee, yArrivee);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
