/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.image.BufferedImage;

/**
 *
 * @author tanguyhelesbeux
 */
public class VueDepot extends VueLieu {
    
    
    private static final String normalImagePath = "Images/factory_40px.png";
    private static final String highlightedImagePath = "Images/factory_highlighted_40px.png";
    private static final String selectedImagePath = "Images/factory_selected_40px.png";
    private static final String selectedHighlightedImagePath = "Images/factory_selectedhighlighted_40px.png";
    
    private static final int Size = 40;

    /**
     * Creates new form VueDepot
     */
    public VueDepot() {
        initComponents();
        this.setOpaque(false);
        this.setSize(Size, Size);
    }
    
    
    @Override
    protected BufferedImage pinImageForActualState() {
        
        if (this.selected && this.highlighted) {
            return this.pinImage(selectedHighlightedImagePath);
        } else if (this.selected) {
            return this.pinImage(selectedImagePath);
        } else if (this.highlighted) {
            return this.pinImage(highlightedImagePath);
        } else {
            return this.pinImage(normalImagePath);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
