/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControleurFenetrePrincipale;
import controller.ControleurPlan;
import java.util.ArrayList;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;

/**
 *
 * @author tanguyhelesbeux
 */
public class VueFenetrePrincipale extends javax.swing.JFrame {
    
    private ControleurFenetrePrincipale controleurFenetrePrincipale;
    
    public static enum MessageType {
     MessageTypeError, MessageTypeWarning, MessageTypeSuccess, MessageTypeLog
}

    private ArrayList<String> colorMsg = new ArrayList();
    /**
     * Creates new form VueFenetrePrincipale
     */
    public VueFenetrePrincipale() {
        
        initComponents();
        
        initColors();
        
        this.controleurFenetrePrincipale = new ControleurFenetrePrincipale(this);
    }
    
    private void initColors() {
        colorMsg.add("#a00a11"); // ERROR
        colorMsg.add("#d49e15"); // WARNING
        colorMsg.add("#2ca024"); // SUCCESS
        colorMsg.add("#333333"); // LOG
    }

    public void setMessage(String msg, MessageType msgType) {
        javax.swing.JEditorPane editorPane = this.commentArea;
        editorPane.setEditable(false);
        editorPane.setContentType("text/html");
        String text = "<font color='"+colorMsg.get(msgType.ordinal())+"'>" + msg + "</font><br>";
        editorPane.setText(text + this.commentArea.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        scrollPanePlan = new javax.swing.JScrollPane();
        scrollPaneInspecteur = new javax.swing.JScrollPane();
        scrollPaneComment = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JEditorPane();
        menuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        itemChargerPlan = new javax.swing.JMenuItem();
        itemChargerLivraisons = new javax.swing.JMenuItem();
        menuEdition = new javax.swing.JMenu();
        itemRefaire = new javax.swing.JMenuItem();
        itemAnnuler = new javax.swing.JMenuItem();
        menuVenu = new javax.swing.JMenu();
        itemZoomOut = new javax.swing.JMenuItem();
        itemZoomIn = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        scrollPanePlan.setMaximumSize(new java.awt.Dimension(800, 678));
        scrollPanePlan.setMinimumSize(new java.awt.Dimension(200, 100));
        scrollPanePlan.setPreferredSize(new java.awt.Dimension(800, 678));
        scrollPanePlan.setSize(new java.awt.Dimension(800, 678));

        commentArea.setMaximumSize(new java.awt.Dimension(800, 88));
        commentArea.setMinimumSize(new java.awt.Dimension(200, 88));
        commentArea.setPreferredSize(new java.awt.Dimension(800, 88));
        commentArea.setSize(new java.awt.Dimension(800, 88));
        scrollPaneComment.setViewportView(commentArea);

        menuFichier.setText("Fichier");

        itemChargerPlan.setText("Charger plan...");
        itemChargerPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemChargerPlanMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemChargerPlanClickedHandler(evt);
            }
        });
        menuFichier.add(itemChargerPlan);

        itemChargerLivraisons.setText("Charger livraisons...");
        itemChargerLivraisons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemChargerLivraisonsMousePressed(evt);
            }
        });
        itemChargerLivraisons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemChargerLivraisonsActionPerformed(evt);
            }
        });
        menuFichier.add(itemChargerLivraisons);

        menuBar.add(menuFichier);

        menuEdition.setText("Edition");

        itemRefaire.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        itemRefaire.setText("Refaire");
        menuEdition.add(itemRefaire);

        itemAnnuler.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        itemAnnuler.setText("Annuler");
        menuEdition.add(itemAnnuler);

        menuBar.add(menuEdition);

        menuVenu.setText("Vue");

        itemZoomOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        itemZoomOut.setText("Zoom Out");
        itemZoomOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemZoomOutMousePressed(evt);
            }
        });
        itemZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemZoomOutActionPerformed(evt);
            }
        });
        menuVenu.add(itemZoomOut);

        itemZoomIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_EQUALS, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemZoomIn.setText("Zoom In");
        itemZoomIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemZoomInMousePressed(evt);
            }
        });
        itemZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemZoomInActionPerformed(evt);
            }
        });
        menuVenu.add(itemZoomIn);

        menuBar.add(menuVenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneComment)
                    .addComponent(scrollPanePlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneInspecteur, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneInspecteur)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPanePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneComment, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemChargerLivraisonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemChargerLivraisonsActionPerformed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldLoadLivraison();
    }//GEN-LAST:event_itemChargerLivraisonsActionPerformed

    private void itemChargerPlanClickedHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemChargerPlanClickedHandler
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldLoadPlan();
    }//GEN-LAST:event_itemChargerPlanClickedHandler

    private void itemChargerPlanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemChargerPlanMousePressed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldLoadPlan();
    }//GEN-LAST:event_itemChargerPlanMousePressed

    private void itemChargerLivraisonsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemChargerLivraisonsMousePressed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldLoadLivraison();
    }//GEN-LAST:event_itemChargerLivraisonsMousePressed

    private void itemZoomOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemZoomOutMousePressed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldZoomOut();
    }//GEN-LAST:event_itemZoomOutMousePressed

    private void itemZoomInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemZoomInMousePressed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldZoomIn();
    }//GEN-LAST:event_itemZoomInMousePressed

    private void itemZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemZoomOutActionPerformed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldZoomOut();
    }//GEN-LAST:event_itemZoomOutActionPerformed

    private void itemZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemZoomInActionPerformed
        // TODO add your handling code here:
        this.controleurFenetrePrincipale.shouldZoomIn();
    }//GEN-LAST:event_itemZoomInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueFenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueFenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueFenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueFenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VueFenetrePrincipale fenetre = new VueFenetrePrincipale();
                fenetre.setVisible(true);
                
                
            }
        });
    }

    public JScrollPane getScrollPanePlan() {
        return scrollPanePlan;
    }

    public JEditorPane getCommentArea() {
        return commentArea;
    }

    public JScrollPane getScrollPaneInspecteur() {
        return scrollPaneInspecteur;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane commentArea;
    private javax.swing.JMenuItem itemAnnuler;
    private javax.swing.JMenuItem itemChargerLivraisons;
    private javax.swing.JMenuItem itemChargerPlan;
    private javax.swing.JMenuItem itemRefaire;
    private javax.swing.JMenuItem itemZoomIn;
    private javax.swing.JMenuItem itemZoomOut;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenu menuVenu;
    private javax.swing.JScrollPane scrollPaneComment;
    private javax.swing.JScrollPane scrollPaneInspecteur;
    private javax.swing.JScrollPane scrollPanePlan;
    // End of variables declaration//GEN-END:variables
}
