/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControleurPlan;
import model.Noeud;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;

/**
 *
 * @author tanguyhelesbeux
 */
public class VueNoeud extends javax.swing.JPanel {
    
    public boolean highlighted;
    public boolean selected;
    
    private final Color normalColor = new Color(220, 160, 60);
    private final Color highlightedColor = new Color(255, 220, 160);
    private final Color selectedColor = new Color(30, 80, 170);
    private final Color selectedHighlightedColor = new Color(80, 150, 255);
    
    private VuePlan vuePlan;
    private Noeud noeud;

    /**
     * Creates new form NoeudView
     */
    public VueNoeud() {
        this.initialize();
    }
    
    public VueNoeud(Noeud noeud) {
        this.setNoeud(noeud);
        this.initialize();
    }
    
    private void initialize() {
        initComponents();

        this.setOpaque(false);
        this.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedHangler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitedHandler(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEnterHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEnterHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEnterHandler
        // TODO add your handling code here:
        this.setHighlighted(true);
    }//GEN-LAST:event_mouseEnterHandler

    private void mouseExitedHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitedHandler
        // TODO add your handling code here:
        this.setHighlighted(false);
    }//GEN-LAST:event_mouseExitedHandler

    private void mouseClickedHangler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedHangler
        // TODO add your handling code here:
        this.setSelected(!this.selected);
    }//GEN-LAST:event_mouseClickedHangler

 
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setPlan(VuePlan plan) {
        this.vuePlan = plan;
    }

    public void setNoeud(Noeud noeud) {
        this.noeud = noeud;
    }

    public Noeud getNoeud() {
        return noeud;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        
        this.repaint();
        
        if (selected) {
            this.vuePlan.getControleur().didSelectVueNoeud(this);
        } else {
            this.vuePlan.getControleur().didDeselectVueNoeud(this);
        }
    }
    
    public void setHighlighted(boolean highlighted) {
        this.highlighted = highlighted;
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        this.repaint();
    }
    
    private Color colorForActualState() {
        if (this.selected && this.highlighted) {
            return this.selectedHighlightedColor;
        } else if (this.selected) {
            return this.selectedColor;
        } else if (this.highlighted) {
            return this.highlightedColor;
        } else {
            return this.normalColor;
        }
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(this.colorForActualState());
        g.fillOval(0,0,this.getWidth(),this.getHeight());
    }
}
