/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControleurPlan;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author tanguyhelesbeux
 */
public class VuePlan extends javax.swing.JPanel {
    
    private ControleurPlan controleur;
    
    private static final Color BackgroundColor = new Color(233, 229, 220);

    public void setControleur(ControleurPlan controleur) {
        this.controleur = controleur;
    }

    public ControleurPlan getControleur() {
        return controleur;
    }
    
    public void addVueNoeud(VueNoeud vueNoeud) {
        this.add(vueNoeud);
        this.displayVueNoeud(vueNoeud);
    }
    
    private void displayVueNoeud(VueNoeud vueNoeud) {
            vueNoeud.setPlan(this);
            vueNoeud.setVisible(true);
    }

    /**
     * Creates new form VuePlan
     */
    public VuePlan() {
        initComponents();
        this.setBackground(BackgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
